apiVersion: v1
kind: Service
metadata:
  name: groco
spec:
  type: NodePort
  selector:
    app: groco
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: groco
  labels:
    app: groco
spec:
  selector:
    matchLabels:
      app: groco
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: groco
        tier: frontend
    spec:
      containers:
      - image: ansolomi06/my-python-app:1.0
        name: groco
        ports:
        - containerPort: 8080
        
