apiVersion: apps/v1
kind: Deployment
metadata:
  name: groco
  labels:
    app: groco
spec:
  replicas: 3
  selector:
    matchLabels:
      app: groco
  template:
    metadata:
      labels:
        app: groco
    spec:
      containers:
        - name: groco
          image: ansolomi06/my-python-app:1.0
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: groco
spec:
  type: NodePort
  selector:
    app: groco
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: groco-hpa
spec:
  minReplicas: 3
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: groco
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
